### ISSUE TITLE
ERROR_PRIVILEGE_NOT_HELD when CreateProcessAsUser in CreateUIAccessToken on Win11 22H2

### ISSUE THREAD

**Issue by arlenWKX** [killtimer0/uiaccess#1]
![image](https://user-images.githubusercontent.com/59471373/210795898-10c36286-332b-4583-90e5-5abd51b1c76e.png)

**Comment by killtimer0** [comment]
Did you tried running as administrator?

**Comment by arlenWKX** [comment]
Yes.

**Comment by killtimer0** [comment]
It should be that the current user does not have "replace a process level token" right. I changed the implement of code. It should be OK now.
